### ISSUE TITLE
ログイン時のバリデーションルール

### ISSUE THREAD

**Issue by hokto** [hagitaku/movie_management#15]
ログインする時に入力するフォームのバリデーションルールを設定．
完了次第項目ごとにチェック
- [x] loginId
- [x] password

**Comment by hokto** [comment]
とりあえず必要そうなもの
- loginId

1. 最大文字数指定 16
2. 使用可能な文字の種類制限(アルファベット+数字+記号)

- password
1. 最小・最大文字数指定 min : 8,max : 32
2. 使用可能な文字の種類制限(アルファベット+数字+記号?)
3. 含めないといけない文字 アルファベット,数字 それぞれ1文字以上

**Comment by hagitaku** [comment]
使用可能な記号
_-@$
